### ISSUE TITLE
Time Mask

### ISSUE THREAD

**Issue by roberkules** [brandynbennett/ember-inputmask#45]
Hi,

is it possible to use the date extensions the underlying inputmask library provides. I would like to mask "hh:mm TT" but don't know how or if it's currently possible.

Any help appreciated.

**Comment by brandynbennett** [comment]
Using the new `one-way-input-mask` you could pass whatever `options` hash you want which will be passed through to the underlying library. Does that work for your situation?

**Comment by belgoros** [comment]
I tried to define it as folows:
```
<div class="form-group col-sm-2">
          {{one-way-input-mask
            myTime mask='[9]9:[99]'
            update=(action (mut myTime))
            class="form-control"
          }}
        </div>
```
and it ignores optional values (between the brackets). So I'll have to enter `07:00`(all the 4 digits) instead of just 7. How is it possible to skip or move between defined mask values in the textfield ? Even if I put the cursor on the `7` skipping the prefix `0`, it puts the value as `70:00`.

**Comment by brandynbennett** [comment]
@belgoros 

So it looks like this is an issue with the way Inputmask.js formats the unformatted value. In your example the time you are passing in is the unmasked value, so if it's `7` eventhough you typed `_7:00` Inputmask.js will turn `7` into `7_:__` because it doesn't know which position it should go in. You can remedy this by having an action that sets the maskedValue instead and passing it back into the component

```
    updateTime(unmasked, masked) {
      set(this, 'myTime', unmasked);
      set(this, 'formattedTime', masked);
    },
```

```
{{one-way-input-mask formattedTime
  mask='[9]9:[99]'
  update=(action 'updateTime')
  class="form-control"}}
```

**Comment by belgoros** [comment]
@brandynbennett Thank you very much fir the reply. I'll use just a [standard `input`  of type `time`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time); - as I think to use an add-on (no matter which one, there are [several](https://stackoverflow.com/questions/31493314/emberjs-timepicker) ones providing more or less the same functionalities) with all the caveats it can bring would be an overkill.
