### ISSUE TITLE
Is one-way necessary?

### ISSUE THREAD

**Issue by lougreenwood** [brandynbennett/ember-inputmask#74]
Perhaps I'm mis-understanding the issue, but are one-way inputs really necessary in this add-on?

Seems that removing 2-way binding to the model is easier handled by something like `ember-changeset`?

If I'm understanding it correctly, it seems one-way inputs un-necessarily expands the scope of what this add-ons main feature... input masking?

Apologies if my question seems brash, I'm just curious :)

**Comment by brandynbennett** [comment]
@lougreenwood Good question. The main reason for using the one-way pattern on these inputs is to give power to the consumer on which value to use for mutating a model. I don't think this is documented very well in the README, so I apologize for that. Because these are not simple inputs where the value you want is always the value being displayed. The `update` action passed in receives both the `unmaskedValue` and the `maskedValue`, that way if you want the masked value you can use that, but if what you're really after is the unmasked version, you can use that as well. This way you can separate your display concerns from your data concerns.

**Comment by scottkidder** [comment]
I think this should still be possible by following the migration recommended by DockYard -https://github.com/DockYard/ember-one-way-controls#migrating

Should be relatively easy to maintain the current behavior while dropping the dependency. I'm doing the same thing in my apps now.

**Comment by brandynbennett** [comment]
not seeing this message on GitHub

**Comment by lougreenwood** [comment]
Makes sense, thanks!
